/**
 * vite-plugin-janus-bundle (§12.4) — SSR-driven handler purge.
 *
 * Text-scans the SSR build's emitted HTML for `data-js` attribute values,
 * splits them into behavior tokens, maps each token to a handler module by the
 * filename-as-manifest convention (`t-roving-focus` -> `handlers/t-roving-focus.ts`),
 * and emits a generated client entry that imports ONLY the referenced modules.
 *
 * The scan/codegen core is a pair of pure functions so the mechanism is
 * bundler-portable (§12.4) and unit-testable independent of Vite.
 */
import fs from 'fs';
import path from 'path';
import { type Plugin } from 'vite';

const DEFAULT_ATTR = 'data-js';
const DEFAULT_IMPORT_BASE = '~/lib2/dom/handlers';

/** Scan HTML/text content for behavior tokens in the configured attribute. */
export function scanDataJsTokens(content: string, attr: string = DEFAULT_ATTR): Set<string> {
	const escaped = attr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	const re = new RegExp(`${escaped}\\s*=\\s*["']([^"']*)["']`, 'g');
	const tokens = new Set<string>();
	let m: RegExpExecArray | null;
	while ((m = re.exec(content)) !== null) {
		for (const token of m[1]!.split(/\s+/)) {
			if (token) tokens.add(token);
		}
	}
	return tokens;
}

/**
 * Generate the client entry source: one static import per scanned token that
 * maps to an existing handler module. Behaviors with no matching file (sidecar
 * params, project-only tokens) are skipped.
 */
export function generateHandlerEntry(
	tokens: Iterable<string>,
	handlerExists: (name: string) => boolean,
	importBase: string = DEFAULT_IMPORT_BASE,
): string {
	const included = [...tokens].filter(handlerExists).sort();
	const lines = ['// AUTO-GENERATED by vite-plugin-janus-bundle — do not edit.'];
	for (const name of included) lines.push(`import '${importBase}/${name}';`);
	return lines.join('\n') + '\n';
}

export interface JanusBundleOptions {
	/** The behavior attribute (must match `setup({ attr })` if overridden). */
	attr?: string;
	/** Absolute path to the handlers directory. */
	handlersDir?: string;
	/** Import specifier base for the generated entry. */
	importBase?: string;
	/** Output file name for the generated entry (relative to outDir). */
	outFile?: string;
	/** Log the generated entry. */
	verbose?: boolean;
}

export default function janusBundlePlugin(options: JanusBundleOptions = {}): Plugin {
	const attr = options.attr ?? DEFAULT_ATTR;
	const handlersDir =
		options.handlersDir ?? path.resolve(process.cwd(), 'src/lib2/dom/handlers');
	const importBase = options.importBase ?? DEFAULT_IMPORT_BASE;
	const outFile = options.outFile ?? 'janus-handlers.js';

	const handlerExists = (name: string) => fs.existsSync(path.join(handlersDir, `${name}.ts`));

	return {
		name: 'janus-bundle',
		apply: 'build',
		enforce: 'post',

		generateBundle(_, bundle) {
			const tokens = new Set<string>();
			for (const fileName in bundle) {
				const chunk = bundle[fileName];
				if (!chunk) continue;
				if (fileName.endsWith('.html') && chunk.type === 'asset') {
					for (const t of scanDataJsTokens(String(chunk.source), attr)) tokens.add(t);
				}
			}
			if (tokens.size === 0) return;

			const source = generateHandlerEntry(tokens, handlerExists, importBase);
			if (options.verbose) console.log(`[janus-bundle] generated entry:\n${source}`);
			this.emitFile({ type: 'asset', fileName: outFile, source });
		},
	};
}
